---
- name: restart cpufrequtils
  service:
    name: cpufrequtils
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload power management
  systemd:
    name: homelab-idle-monitor
    state: restarted