version: "3.8"

x-common-settings: &common-settings
  restart: unless-stopped
  networks:
    - media_net

services:
  jellyfin:
    <<: *common-settings
    extends:
      file: ../compose/jellyfin.yml
      service: jellyfin
    
  calibre:
    <<: *common-settings
    extends:
      file: ../compose/calibre.yml
      service: calibre-web

networks:
  media_net:
    driver: bridge